### ISSUE TITLE
Improve priorityq tests as needed

### ISSUE THREAD

**Issue by jonathanstallings** [jonathanstallings/data-structures#14]

**Comment by jay-tyler** [comment]
Reminder: will add tests for instantiation; i.e. arguments such as [1,3,5,QNode(1,2), [[1,32,5], 0], 4] should all work

**Comment by jay-tyler** [comment]
Finished [here](https://github.com/jonathanstallings/data-structures/commit/eb65555c5056e0786ea14b18c57d274bbcc68962).
